from global_scraper import parse_data
from combine_previous_seasons import merge_season
import pandas as pd


player_mapping_24 = {
    'Aleksandar Mitrovic': 'Aleksandar Mitrović',
    'Álex Moreno': 'Álex Moreno Lopera',
    'Alisson': 'Alisson Ramses Becker',
    'Amad Diallo Traore': 'Amad Diallo',
    'Amari&#039;i Bell': "Amari'i Bell",
    'Ameen Al Dakhil': 'Ameen Al-Dakhil',
    'André': 'André Trindade da Costa Neto',
    'André Gomes': 'André Tavares Gomes',
    'Andreas Pereira': 'Andreas Hoelgebaum Pereira',
    'Anel Ahmedhodzic': 'Anel Ahmedhodžić',
    'Anis Ben Slimane': 'Anis Slimane',
    'Anssumane Fati': 'Anssumane Fati Vieira',
    'Antony': 'Antony Matheus dos Santos',
    'Ben Brereton': 'Ben Brereton Díaz',
    'Ben White': 'Benjamin White',
    'Benoit Badiashile Mukinayi': 'Benoît Badiashile',
    'Benson Manuel': 'Manuel Benson Hedilazio',
    'Bernardo Silva': 'Bernardo Veiga de Carvalho e Silva',
    'Beto': 'Norberto Bercique Gomes Betuncal',
    'Bobby Reid': 'Bobby De Cordova-Reid',
    'Boubacar Traore': 'Boubacar Traoré',
    'Boubakary Soumare': 'Boubakary Soumaré',
    'Brandon Aguilera': 'Brandon Aguilera Zamora',
    'Bruno Fernandes': 'Bruno Borges Fernandes',
    'Bruno Guimarães': 'Bruno Guimarães Rodriguez Moura',
    'Carlos Forbs': 'Carlos Roberto Forbs Borges',
    'Carlos Vinicius': 'Carlos Vinícius Alves Morais',
    'Casemiro': 'Carlos Henrique Casimiro',
    'Cheick Oumar Doucoure': 'Cheick Doucouré',
    'Chimuanya Ugochukwu': 'Lesley Ugochukwu',
    'Clement Lenglet': 'Clément Lenglet',
    'Cédric Soares': 'Cédric Alves Soares',
    'Danilo': 'Danilo dos Santos de Oliveira',
    'Dara O&#039;Shea': "Dara O'Shea",
    'Dara O\'Shea': 'Dara O\'Shea',
    'Darwin Núñez': 'Darwin Núñez Ribeiro',
    'David Raya': 'David Raya Martin',
    'Deivid Washington': 'Deivid Washington de Souza Eugênio',
    'Destiny Udogie': 'Iyenoma Destiny Udogie',
    'Diego Carlos': 'Diego Carlos Santos Silva',
    'Diogo Dalot': 'Diogo Dalot Teixeira',
    'Diogo Jota': 'Diogo Teixeira da Silva',
    'Dominic Solanke': 'Dominic Solanke-Mitchell',
    'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
    'Ederson': 'Ederson Santana de Moraes',
    'Edson Álvarez': 'Edson Álvarez Velázquez',
    'Emile Smith-Rowe': 'Emile Smith Rowe',
    'Emiliano Buendía': 'Emiliano Buendía Stati',
    'Emiliano Martinez': 'Emiliano Martínez Romero',
    'Estupiñán': 'Pervis Estupiñán',
    'Evanilson': 'Francisco Evanilson de Lima Barbosa',
    'Fabio Carvalho': 'Fábio Freitas Gouveia Carvalho',
    'Fabio Silva': 'Fábio Silva',
    'Fábio Vieira': 'Fábio Ferreira Vieira',
    'Facundo Pellistri': 'Facundo Pellistri Rebollo',
    'Felipe': 'Felipe Augusto de Almeida Monteiro',
    'Fode Toure': 'Fodé Ballo-Touré',
    'Gabriel': 'Gabriel dos Santos Magalhães',
    'Gabriel Jesus': 'Gabriel Fernando de Jesus',
    'Gabriel Martinelli': 'Gabriel Martinelli Silva',
    'Gonçalo Guedes': 'Gonçalo Manuel Ganchinho Guedes',
    'Hee-Chan Hwang': 'Hwang Hee-chan',
    'Hugo Bueno': 'Hugo Bueno López',
    'Ibrahim Sangare': 'Ibrahim Sangaré',
    'Igor Julio': 'Igor Julio dos Santos de Paulo',
    'Ionut Radu': 'Ionuț Radu',
    'Ismaila Sarr': 'Ismaïla Sarr',
    'Issa Kabore': 'Issa Kaboré',
    'Ivan Perisic': 'Ivan Perišić',
    'Iyenoma Destiny Udogie': 'Destiny Udogie',
    'Jack Colback': 'Jack Colback',
    'Jaden Philogene-Bidace': 'Jaden Philogene',
    'Jefferson Lerma': 'Jefferson Lerma Solís',
    'Jesper Lindstrom': 'Jesper Lindstrøm',
    'Jéremy Doku': 'Jérémy Doku',
    'Joe Ayodele-Aribo': 'Joe Aribo',
    'Joelinton': 'Joelinton Cássio Apolinário de Lira',
    'Johann Berg Gudmundsson': 'Jóhann Berg Gudmundsson',
    'João Félix': 'João Félix Sequeira',
    'João Gomes': 'João Victor Gomes da Silva',
    'João Palhinha': 'João Palhinha Gonçalves',
    'João Pedro': 'João Pedro Junqueira de Jesus',
    'Jordan Beyer': 'Louis Beyer',
    'José Sá': 'José Malheiro de Sá',
    'Josko Gvardiol': 'Joško Gvardiol',
    'Jorginho': 'Jorge Luiz Frello Filho',
    'Jota Silva': 'João Pedro Ferreira Silva',
    'Julián Araujo': 'Julián Araujo Zúñiga',
    'Kaine Hayden': 'Kaine Kesler-Hayden',
    'Kaoru Mitoma': 'Mitoma Kaoru',
    'Kepa': 'Kepa Arrizabalaga',
    'Kosta Nedeljkovic': 'Kosta Nedeljković',
    'Louis Beyer': 'Jordan Beyer',
    'Lucas Paquetá': 'Lucas Tolentino Coelho de Lima',
    'Mads Andersen': 'Mads Juel Andersen',
    'Mads Roerslev': 'Mads Roerslev Rasmussen',
    'Marc Cucurella': 'Marc Cucurella Saseta',
    'Marc Guehi': 'Marc Guéhi',
    'Martin Odegaard': 'Martin Ødegaard',
    'Mateo Kovacic': 'Mateo Kovačić',
    'Mateus Fernandes': 'Mateus Gonçalo Espanha Fernandes',
    'Matheus Cunha': 'Matheus Santos Carneiro Da Cunha',
    'Matheus França': 'Matheus França de Oliveira',
    'Matheus Nunes': 'Matheus Luiz Nunes',
    'Matthew Cash': 'Matty Cash',
    'Maxime Estève': 'Maxime Esteve',
    'Miguel Almirón': 'Miguel Almirón Rejala',
    'Moisés Caicedo': 'Moisés Caicedo Corozo',
    'Morato': 'Felipe Rodrigues da Silva',
    'Moussa Niakhate': 'Moussa Niakhaté',
    'Murillo': 'Murillo Santiago Costa dos Santos',
    'Naif Aguerd': 'Nayef Aguerd',
    'Nélson Semedo': 'Nélson Cabral Semedo',
    'Neto': 'Norberto Murara Neto',
    'Nicolo Zaniolo': 'Nicolò Zaniolo',
    'Nikola Milenkovic': 'Nikola Milenković',
    'Nuno Tavares': 'Nuno Varela Tavares',
    'Odysseas Vlachodimos': 'Odysseas Vlachodimos',
    'Odisseas Vlachodimos': 'Odysseas Vlachodimos',
    'Omari Hutchinson': 'Omari Giraud-Hutchinson',
    'Pablo Fornals': 'Pablo Fornals Malla',
    'Pape Sarr': 'Pape Matar Sarr',
    'Pedro Neto': 'Pedro Lomba Neto',
    'Philippe Coutinho': 'Philippe Coutinho Correia',
    'Raphael Varane': 'Raphaël Varane',
    'Rayan Ait Nouri': 'Rayan Aït-Nouri',
    'Renato Veiga': 'Renato Palma Veiga',
    'Richarlison': 'Richarlison de Andrade',
    'Rodrigo Gomes': 'Rodrigo Martins Gomes',
    'Rodrigo Muniz': 'Rodrigo Muniz Carvalho',
    'Rodri': 'Rodrigo Hernandez',
    'Romeo Lavia': 'Roméo Lavia',
    'Rúben Dias': 'Rúben Gato Alves Dias',
    'Ryan Giles': 'Ryan John Giles',
    'Said Benrahma': 'Saïd Benrahma',
    'Sammie Szmodics': 'Sam Szmodics',
    'Sasa Lukic': 'Saša Lukić',
    'Sávio': "Sávio 'Savinho' Moreira de Oliveira",
    'Son Heung-Min': 'Son Heung-min',
    'Sugawara Yukinari': 'Yukinari Sugawara',
    'Thiago Alcántara': 'Thiago Alcántara do Nascimento',
    'Thiago Silva': 'Thiago Emiliano da Silva',
    'Tomas Soucek': 'Tomáš Souček',
    'Toti': 'Toti António Gomes',
    'Valentino Livramento': 'Tino Livramento',
    'Vinicius Souza': 'Vini de Souza Costa',
    'Vitinho': 'Victor da Silva',
    'Vladimir Coufal': 'Vladimír Coufal',
    'Wataru Endo': 'Endo Wataru',
    'Wilfred Ndidi': 'Wilfred Ndidi',
    'William Smallbone': 'Will Smallbone',
    'Willian': 'Willian Borges da Silva',
    'Yehor Yarmolyuk': 'Yehor Yarmoliuk',
    'Youssef Chermiti': 'Youssef Ramalho Chermiti',
    'Yukinari Sugawara': 'Sugawara Yukinari',
    'Yunus Konak': 'Yunus Emre Konak',
    'Zanka': 'Mathias Jorgensen'
}

# Player mapping for several FPL names for one player
fpl_name_mapping = {
    'Adama Traoré Diarra': 'Adama Traoré',
    'André Filipe Tavares Gomes': 'André Tavares Gomes',
    'Arnaut Danjuma Groeneveld': 'Arnaut Danjuma',
    'Benjamin Chilwell': 'Ben Chilwell',
    'Benjamin White': 'Ben White',
    'Bernardo Mota Veiga de Carvalho e Silva': 'Bernardo Veiga de Carvalho e Silva',
    'Bruno Miguel Borges Fernandes': 'Bruno Borges Fernandes',
    'Cédric Alves Soares': 'Cédric Soares',
    'David de Gea': 'David De Gea Quintana',
    'Diogo Teixeira da Silva': 'Diogo Jota',
    'Emerson Aparecido Leite de Souza Junior': 'Emerson Leite de Souza Junior',
    'Emiliano Martínez Romero': 'Emiliano Martínez',
    'Gabriel Teodoro Martinelli Silva': 'Gabriel Martinelli Silva',
    'Héctor Junior Firpo Adames': 'Junior Firpo Adames',
    'Hee-Chan Hwang': 'Hwang Hee-Chan',
    'Hwang Hee-chan': 'Hwang Hee-Chan',
    'Heung-Min Son': 'Son Heung-Min',
    'Son Heung-min': 'Son Heung-Min',
    'Jeremy Sarmiento Morante': 'Jeremy Sarmiento',
    'João Pedro Cavaco Cancelo': 'João Cancelo',
    'Joseph Gomez': 'Joe Gomez',
    'Joseph Willock': 'Joe Willock',
    'Luis Sinisterra Lucumí': 'Luis Sinisterra',
    'Lyanco Evangelista Silveira Neves Vojnovic': 'Lyanco Silveira Neves Vojnovic',
    'Marc Cucurella Saseta': 'Marc Cucurella',
    'Mateo Kovačić': 'Mateo Kovacic',
    'Matthew Cash': 'Matty Cash',
    'Miguel Almirón Rejala': 'Miguel Almirón',
    'Mohamed Naser El Sayed Elneny': 'Mohamed Elneny',
    'Moisés Caicedo Corozo': 'Moisés Caicedo',
    'Pablo Fornals Malla': 'Pablo Fornals',
    'Rayan Ait Nouri': 'Rayan Aït-Nouri',
    'Ricardo Domingos Barbosa Pereira': 'Ricardo Barbosa Pereira',
    'Rúben Diogo da Silva Neves': 'Rúben da Silva Neves',
    'Rúben Santos Gato Alves Dias': 'Rúben Gato Alves Dias',
    'Sergi Canós Tenés': 'Sergi Canós',
    'Vladimir Coufal': 'Vladimír Coufal',   
}

# Define team mapping
team_mapping = {
    'Arsenal': 1,
    'Aston Villa': 2,
    'Bournemouth': 3,
    'Brentford': 4,
    'Brighton': 5,
    'Chelsea': 6,
    'Crystal Palace': 7,
    'Everton': 8,
    'Fulham': 9,
    'Ipswich': 10,
    'Leicester': 11,
    'Liverpool': 12,
    'Man City': 13,
    'Man Utd': 14,
    'Newcastle': 15,
    'Nott\'m Forest': 16,
    'Southampton': 17,
    'Spurs': 18,
    'West Ham': 19,
    'Wolves': 20,
    'Burnley': 21,
    'Luton': 22,
    'Sheffield Utd': 23,
    'Leeds': 24,
    'Watford': 25,
    'West Brom': 26,
    'Norwich': 27
}

# Define position mapping
pos_mapping = {'GK': 1,
              'GKP': 1,
              'DEF': 2,
              'MID': 3,
              'FWD': 4}


def main():
    # Parse to get newest data
    parse_data()

    # Merge newest season FPL and Understat data
    df_24 = merge_season('2024-25', player_mapping_24)

    # Combine all seasons
    df_prev_seasons = pd.read_csv("data/prev_seasons_merged.csv")
    df_all = pd.concat([df_prev_seasons, df_24], ignore_index=True)
    df_all.reset_index(drop=True, inplace=True)
    df_all = df_all.fillna(0)
    
    # Add team and position IDs, update names
    df_all['name'] = df_all['name'].map(fpl_name_mapping).fillna(df_all['name'])
    df_all['team_id'] = df_all['team'].map(team_mapping)
    df_all['opp_team_id'] = df_all['opponent_team'].map(team_mapping)
    df_all['pos_id'] = df_all['position'].map(pos_mapping)

    # Create team goal and opp goal columns
    df_all['team_goals'] = df_all.apply(
        lambda row: row['team_h_score'] if row['was_home'] else row['team_a_score'], axis=1
    )
    df_all['opponent_goals'] = df_all.apply(
        lambda row: row['team_a_score'] if row['was_home'] else row['team_h_score'], axis=1
    )

    # Save to flle
    df_all.to_csv("data/all_seasons_merged.csv", index=False)

if __name__ == "__main__":
    main()